version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD: 'YourStrong@Passw0rd'
        MSSQL_PID: Express
    ports:
        - 1433:1433
    volumes:
       - db-data:/var/lib/mssql/data
  db2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD: 'YourStrong@Passw0rd'
        MSSQL_PID: Express
    ports:
        - 1402:1433
  musiccatalog.identityapi:
    image: ${DOCKER_REGISTRY-}musiccatalogidentityapi
    container_name: identity-api
    build:
      context: .
      dockerfile: src/MusicCatalog.IdentityApi/Dockerfile
    ports:
        - 5000:80
    depends_on: 
        - db
  musiccatalog.webapi:
    image: ${DOCKER_REGISTRY-}musiccatalogwebapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/MusicCatalog.WebApi/Dockerfile
    ports:
        - 5001:80
    depends_on: 
        - db2

volumes:
 db-data:

networks:
 api-network:
  driver: bridge