version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'YourStrong@Passw0rd'
        MSSQL_PID: Express
    ports:
        - 1433:1433
    volumes:
       - db-data:/var/lib/mssql/data
  musiccatalog.identityapi:
    image: ${DOCKER_REGISTRY-}musiccatalogidentityapi
    build:
      context: .
      dockerfile: src/MusicCatalog.IdentityApi/Dockerfile
    ports:
        - 5000:80
    depends_on: 
        - db
  musiccatalog.webapi:
    image: ${DOCKER_REGISTRY-}musiccatalogwebapi
    build:
      context: .
      dockerfile: src/MusicCatalog.WebApi/Dockerfile
    ports:
        - 5001:80
    depends_on: 
        - db
volumes:
 db-data: