version: '3.4'

services:
  musiccatalog.identityapi:
    container_name: identity-api
    image: ${DOCKER_REGISTRY-}music-catalog-identity-api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - 5000:80
    expose:
        - 5000
    build:
      context: .
      dockerfile: src/MusicCatalog.IdentityApi/Dockerfile
    depends_on: 
        - musiccatalog.database
  musiccatalog.database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'YourStrong@Passw0rd'
    expose:  
        - 1433
    ports:
        - "${DOCKER_SQL_PORT:-1433}:1433"