version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD: 'YourStrong@Passw0rd'
        MSSQL_PID: Express
    ports:
        - 1433:1433
    volumes:
        - db-data:/var/lib/mssql/data
  db-api:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD: 'YourStrong@Passw0rd'
        MSSQL_PID: Express
    ports:
        - 1434:1433
    volumes:
        - db-api-data:/var/lib/mssql/data
  musiccatalog.identityapi:
    image: ${DOCKER_REGISTRY-}musiccatalog-identityapi
    container_name: identity-api
    build:
      context: .
      dockerfile: src/MusicCatalog.IdentityApi/Dockerfile
    ports:
        - 5000:80
    depends_on: 
        - db
  musiccatalog.webapi:
    image: ${DOCKER_REGISTRY-}musiccatalog-webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/MusicCatalog.WebApi/Dockerfile
    ports:
        - 5001:80
    
  musiccatalog-angularclient:
    image: ${DOCKER_REGISTRY-}musiccatalog-angularclient
    container_name: angular-client
    build:
      context: src/MusicCatalog-AngularClient
      dockerfile: ./Dockerfile
    ports:
        - 8080:80
    depends_on:
        -  musiccatalog.webapi
        -  musiccatalog.identityapi

volumes:
 db-data:
 db-api-data: