# Build
FROM node:14.18.1-alpine as build
WORKDIR /usr/src/app
RUN npm cache clean --force
COPY package.json package-lock.json ./
RUN npm install
COPY . . 
RUN npm run build

# Run
FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/musiccatalog-angularclient /usr/share/nginx/musiccatalog-angularclient
EXPOSE 80