apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment
  labels:
    app: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: kveremeyeva/musiccatalog-identityapi:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api-service
  labels:
    app: identity-api
spec:
  type: NodePort
  selector:
    app: identity-api
  ports:
  - port: 80
    nodePort: 30753
    protocol: TCP