apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment
  labels:
    app: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: musiccatalog.identityapi
  template:
    metadata:
      labels:
        app: identity-api
        service: musiccatalog.identityapi
    spec:
      containers:
        - name: identity-api
          image: kveremeyeva/musiccatalog-identityapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api-service
  labels:
    app: identity-api
    service: musiccatalog.identityapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: musiccatalog.identityapi
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: identity-api-ingress
spec:
    rules:
    - http:
        paths:
        - path: /identity-api
          pathType: Prefix
          backend:
            service:
              name: identity-api-service
              port:
                number: 80
