apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
  labels:
    app: web-api-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api-pod
  template:
    metadata:
      labels:
        app: web-api-pod
    spec:
      containers:
      - name: web-api
        image: kveremeyeva/musiccatalog-webapi:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-service
  labels:
    app: web-api-pod
spec:
  selector:
    app: web-api-pod
  ports:
    - port: 5001
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: web-api-ingress
spec:
    rules:
    - http:
        paths:
        - path: /web-api
          pathType: Prefix
          backend:
            service:
              name: web-api-service
              port:
                number: 80