CREATE DATABASE TestMusicCatalog;

CREATE TABLE [dbo].[Genres]
(
	[GenreId] INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(15) NOT NULL
)

CREATE TABLE [dbo].[Performers]
(
	[PerformerId] INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE [dbo].[Songs]
(
	[SongId] INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(15) NOT NULL,
	[GenreId] INT NOT NULL,
	[PerformerId] INT NOT NULL,
)

CREATE TABLE [dbo].[Albums]
(
	[AlbumId] INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL,
	[ReleaseDate] DATE NOT NULL,
	[SongId] INT NOT NULL,
)

ALTER TABLE Songs
ADD CONSTRAINT FK_GenreSong
FOREIGN KEY (GenreId) REFERENCES Genres(GenreId);

ALTER TABLE Songs
ADD CONSTRAINT FK_PerformerSong
FOREIGN KEY (PerformerId) REFERENCES Performers(PerformerId);

ALTER TABLE Albums
ADD CONSTRAINT FK_SongAlbum
FOREIGN KEY (SongId) REFERENCES Songs(SongId);